### ISSUE TITLE
from driver.cam import cams

### ISSUE THREAD

**Issue by 571946808** [reece15/cnn_face_detection#1]

**Comment by reece15** [comment]
有什么问题吗？ @571946808

**Comment by zhenyangGao** [comment]
can it only use cpu? i don't have a gpu. 571946808 is your qq?

**Comment by reece15** [comment]
是的，可以。但是非常慢。我的qq 是364986007

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: zhenyangGao <notifications@github.com>
发送时间: Friday, January 4, 2019 10:46:10 PM
收件人: reece15/cnn_face_detection
抄送: reece; Comment
主题: Re: [reece15/cnn_face_detection] from driver.cam import cams (#1)


can it only use cpu? i don't have a gpu. 571946808 is your qq?

―

**Comment by reece15** [comment]
项目里有

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 571946808 <notifications@github.com>
发送时间: Monday, September 10, 2018 11:16:39 AM
收件人: reece15/cnn_face_detection
抄送: Subscribed
主题: [reece15/cnn_face_detection] 你好 (#1)


from driver.cam import cams，请问一下这个是什么包，我找不到，谢谢~~

―
